### ISSUE TITLE
Question about expected method calls received

### ISSUE THREAD

**Issue by paddor** [rspec-given/rspec-given#16]
I'd like to verify that an object actually received a specific method call. It looks like this isn't very straight forward with the Given/When/Then syntax. One way I got it to work is this:

``` ruby
describe "#signal" do
  Given(:status) { 5 }
  Given(:delegate) { socket.ffi_delegate }
  Given { expect(Lowlevel::SocketClass).to receive(:signal).with(delegate, status) }
  When { socket.signal(status) }
  Then { true }
end
```

Is there a better way, except for falling back to the more standard way of thing it like this?

``` ruby
describe "#signal" do
  let(:status) { 5 }
  let(:delegate) { socket.ffi_delegate }
  it "sends signal" do
    expect(Lowlevel::SocketClass).to receive(:signal).with(delegate, status)
    socket.signal(status)
  end
end
```

Thanks for any help.

**Comment by paddor** [comment]
@searls Any updates on this?

**Comment by searls** [comment]
Hey, sorry I was on vacation when this came in.

My answer would be to use spies. I've been advocating people use spies in favor of mocks for years, for several reasons, but among them was their ability to preserve given-when-then ordering. I wrote the gem "gimme" as a proof of concept in Ruby, and when Jim was writing rspec-given he adopted that until he added spy support to his flexmock gem. In your case, I'd just recommend you start using spies in rspec-mocks, since you're already using their mocks.

**Comment by paddor** [comment]
I hope you've had a great vacation. :-) Thanks for the hint. Reading up on spies now...
